<?php

 return [
    'cities' => [
        "dhaka" => "Dhaka",
        "chattogram" => "Chattogram",
        "khulna" => "Khulna",
        "rajshahi" => "Rajshahi",
        "sylhet" => "Sylhet",
        "barishal" => "Barishal",
        "rangpur" => "Rangpur",
        "mymensingh" => "Mymensingh",
        "gazipur" => "Gazipur",
        "narayanganj" => "Narayanganj",
        "comilla" => "Comilla",
        "jessore" => "Jessore",
        "coxs_bazar" => "Cox's Bazar",
        "bogura" => "Bogura",
        "jamalpur" => "Jamalpur",
        "narsingdi" => "Narsingdi",
        "tangail" => "Tangail",
        "pabna" => "Pabna",
        "dinajpur" => "Dinajpur",
        "feni" => "Feni",
        "kushtia" => "Kushtia",
        "madaripur" => "Madaripur",
        "faridpur" => "Faridpur",
        "brahmanbaria" => "Brahmanbaria",
        "satkhira" => "Satkhira",
        "gopalganj" => "Gopalganj",
        "noakhali" => "Noakhali",
        "bagerhat" => "Bagerhat",
        "sherpur" => "Sherpur",
        "netrokona" => "Netrokona",
        "lakshmipur" => "Lakshmipur",
        "chandpur" => "Chandpur",
        "barguna" => "Barguna",
        "bhola" => "Bhola",
        "jhalokathi" => "Jhalokathi",
        "pirojpur" => "Pirojpur",
        "sunamganj" => "Sunamganj",
        "habiganj" => "Habiganj",
        "maulvibazar" => "Maulvibazar",
        "kurigram" => "Kurigram",
        "thakurgaon" => "Thakurgaon",
        "panchagarh" => "Panchagarh",
        "lalmonirhat" => "Lalmonirhat",
        "gaibandha" => "Gaibandha",
        "nilphamari" => "Nilphamari",
        "meherpur" => "Meherpur",
        "chuadanga" => "Chuadanga",
        "magura" => "Magura",
        "narail" => "Narail",
        "jhenaidah" => "Jhenaidah",
        "shariatpur" => "Shariatpur",
        "munshiganj" => "Munshiganj",
        "manikganj" => "Manikganj",
        "rajbari" => "Rajbari",
        "natore" => "Natore",
        "joypurhat" => "Joypurhat",
        "chapainawabganj" => "Chapainawabganj",
        "naogaon" => "Naogaon",
        "bandarban" => "Bandarban",
        "khagrachari" => "Khagrachari",
        "rangamati" => "Rangamati"
    ],

 ];

?>